export default {
    splashScreenLogo: require('@assets/images/volleyball.png'),
    contactEmail: require('@assets/images/contact.png'),
    homeLogo: require('@assets/images/home.png'),
    calendar: require('@assets/images/calendar.png'),
    defaultUser: require('@assets/images/user.png'),
    settings: require('@assets/images/settings.png'),

    clock: require('@assets/images/clock.png'),
    leftArrow: require('@assets/images/leftArrow.png'),
    rightArrow: require('@assets/images/rightArrow.png'),
    team: require('@assets/images/team.png'),
    volleyballBall: require('@assets/images/volleyballBall.png'),
    volleyballBall2: require('@assets/images/volleyballBall2.png'),
    information: require('@assets/images/info.png'),
    news: require('@assets/images/news.png'),
    backArrow: require('@assets/images/backArrow.png'),
    forwardArrow: require('@assets/images/forwardArrow.png'),
    tournament: require('@assets/images/tournament.png'),
    newspaper: require('@assets/images/newspaper.png'),
    shortcutBackDesign: require('@assets/images/shortcutBackDesign.png'),
    ArrowBack: require('@assets/images/ArrowBack.svg'),
    Menu: require('@assets/images/Menu.svg'),
    VolleyballBall: require('@assets/images/VolleyballBall.svg'),
};
